// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command_request.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateWorkRequestPb struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWorkRequestPb) Reset()         { *m = CreateWorkRequestPb{} }
func (m *CreateWorkRequestPb) String() string { return proto.CompactTextString(m) }
func (*CreateWorkRequestPb) ProtoMessage()    {}
func (*CreateWorkRequestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_request_f8c6eeec0c1817b0, []int{0}
}
func (m *CreateWorkRequestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWorkRequestPb.Unmarshal(m, b)
}
func (m *CreateWorkRequestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWorkRequestPb.Marshal(b, m, deterministic)
}
func (dst *CreateWorkRequestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWorkRequestPb.Merge(dst, src)
}
func (m *CreateWorkRequestPb) XXX_Size() int {
	return xxx_messageInfo_CreateWorkRequestPb.Size(m)
}
func (m *CreateWorkRequestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWorkRequestPb.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWorkRequestPb proto.InternalMessageInfo

func (m *CreateWorkRequestPb) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateWorkRequestPb struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWorkRequestPb) Reset()         { *m = UpdateWorkRequestPb{} }
func (m *UpdateWorkRequestPb) String() string { return proto.CompactTextString(m) }
func (*UpdateWorkRequestPb) ProtoMessage()    {}
func (*UpdateWorkRequestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_request_f8c6eeec0c1817b0, []int{1}
}
func (m *UpdateWorkRequestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWorkRequestPb.Unmarshal(m, b)
}
func (m *UpdateWorkRequestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWorkRequestPb.Marshal(b, m, deterministic)
}
func (dst *UpdateWorkRequestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWorkRequestPb.Merge(dst, src)
}
func (m *UpdateWorkRequestPb) XXX_Size() int {
	return xxx_messageInfo_UpdateWorkRequestPb.Size(m)
}
func (m *UpdateWorkRequestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWorkRequestPb.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWorkRequestPb proto.InternalMessageInfo

func (m *UpdateWorkRequestPb) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type DeleteWorkRequestPb struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteWorkRequestPb) Reset()         { *m = DeleteWorkRequestPb{} }
func (m *DeleteWorkRequestPb) String() string { return proto.CompactTextString(m) }
func (*DeleteWorkRequestPb) ProtoMessage()    {}
func (*DeleteWorkRequestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_request_f8c6eeec0c1817b0, []int{2}
}
func (m *DeleteWorkRequestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWorkRequestPb.Unmarshal(m, b)
}
func (m *DeleteWorkRequestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWorkRequestPb.Marshal(b, m, deterministic)
}
func (dst *DeleteWorkRequestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWorkRequestPb.Merge(dst, src)
}
func (m *DeleteWorkRequestPb) XXX_Size() int {
	return xxx_messageInfo_DeleteWorkRequestPb.Size(m)
}
func (m *DeleteWorkRequestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWorkRequestPb.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWorkRequestPb proto.InternalMessageInfo

// Start, Pause, Resume, Finish, CancelFinish
type ChangeWorkStateRequestPb struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChangeWorkStateRequestPb) Reset()         { *m = ChangeWorkStateRequestPb{} }
func (m *ChangeWorkStateRequestPb) String() string { return proto.CompactTextString(m) }
func (*ChangeWorkStateRequestPb) ProtoMessage()    {}
func (*ChangeWorkStateRequestPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_command_request_f8c6eeec0c1817b0, []int{3}
}
func (m *ChangeWorkStateRequestPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeWorkStateRequestPb.Unmarshal(m, b)
}
func (m *ChangeWorkStateRequestPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeWorkStateRequestPb.Marshal(b, m, deterministic)
}
func (dst *ChangeWorkStateRequestPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeWorkStateRequestPb.Merge(dst, src)
}
func (m *ChangeWorkStateRequestPb) XXX_Size() int {
	return xxx_messageInfo_ChangeWorkStateRequestPb.Size(m)
}
func (m *ChangeWorkStateRequestPb) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeWorkStateRequestPb.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeWorkStateRequestPb proto.InternalMessageInfo

func (m *ChangeWorkStateRequestPb) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateWorkRequestPb)(nil), "CreateWorkRequestPb")
	proto.RegisterType((*UpdateWorkRequestPb)(nil), "UpdateWorkRequestPb")
	proto.RegisterType((*DeleteWorkRequestPb)(nil), "DeleteWorkRequestPb")
	proto.RegisterType((*ChangeWorkStateRequestPb)(nil), "ChangeWorkStateRequestPb")
}

func init() {
	proto.RegisterFile("command_request.proto", fileDescriptor_command_request_f8c6eeec0c1817b0)
}

var fileDescriptor_command_request_f8c6eeec0c1817b0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x89, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4,
	0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x20, 0x0a, 0x94, 0xb4, 0xb9, 0x84, 0x9d,
	0x8b, 0x52, 0x13, 0x4b, 0x52, 0xc3, 0xf3, 0x8b, 0xb2, 0x83, 0x20, 0x7a, 0x03, 0x92, 0x84, 0x44,
	0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c,
	0x90, 0xe2, 0xd0, 0x82, 0x14, 0x22, 0x15, 0x8b, 0x72, 0x09, 0xbb, 0xa4, 0xe6, 0xa4, 0xa2, 0x29,
	0x56, 0xf2, 0xe2, 0x92, 0x70, 0xce, 0x48, 0xcc, 0x4b, 0x07, 0x0b, 0x07, 0x97, 0x24, 0x96, 0xa4,
	0x22, 0x0c, 0xd2, 0xe3, 0x62, 0x01, 0xb9, 0x0f, 0x6c, 0x0e, 0xb7, 0x91, 0x94, 0x1e, 0xc4, 0xf1,
	0x7a, 0x30, 0xc7, 0xeb, 0x85, 0xc0, 0x1c, 0x1f, 0x04, 0x56, 0xe7, 0xc4, 0x16, 0xc5, 0x92, 0x9b,
	0x98, 0x99, 0x97, 0xc4, 0x06, 0x56, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x85, 0x3a, 0x32,
	0xca, 0x05, 0x01, 0x00, 0x00,
}
