name: workrec

version: 1.0.0+1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  quiver: ^3.0.0

  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4

  clock: ^1.1.0
  fake_async: ^1.2.0
  mockito: ^5.0.10
  stream_transform: ^2.0.0

dev_dependencies:
  test: any

  flutter_lints: ^1.0.2
  build_runner: ^2.0.4

