# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_request.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("command_request.proto", :syntax => :proto3) do
    add_message "CreateWorkRequestPb" do
      optional :title, :string, 1
    end
    add_message "UpdateWorkRequestPb" do
      optional :title, :string, 1
    end
    add_message "DeleteWorkRequestPb" do
    end
    add_message "ChangeWorkStateRequestPb" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
    end
  end
end

CreateWorkRequestPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateWorkRequestPb").msgclass
UpdateWorkRequestPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateWorkRequestPb").msgclass
DeleteWorkRequestPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("DeleteWorkRequestPb").msgclass
ChangeWorkStateRequestPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChangeWorkStateRequestPb").msgclass
