# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worklist.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("worklist.proto", :syntax => :proto3) do
    add_message "WorkListPb" do
      repeated :works, :message, 1, "WorkListItemPb"
      optional :next_page_token, :string, 2
    end
    add_message "WorkListItemPb" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :base_working_time, :message, 3, "google.protobuf.Timestamp"
      optional :paused_at, :message, 4, "google.protobuf.Timestamp"
      optional :state, :enum, 5, "WorkListItemPb.State"
      optional :started_at, :message, 6, "google.protobuf.Timestamp"
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_enum "WorkListItemPb.State" do
      value :STATE_UNSPECIFIED, 0
      value :UNSTARTED, 1
      value :STARTED, 2
      value :PAUSED, 3
      value :RESUMED, 4
      value :FINISHED, 5
    end
  end
end

WorkListPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkListPb").msgclass
WorkListItemPb = Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkListItemPb").msgclass
WorkListItemPb::State = Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkListItemPb.State").enummodule
