extends: 'react-app'
plugins:
  - react-hooks
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
