# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Workrec' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workrec
  pod 'Firebase/Auth'

  target 'WorkrecTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorkrecUITests' do
    # Pods for testing
  end

end
