version: 2
jobs:
  server-test-and-deploy:
    docker:
      - image: circleci/golang:1.11-stretch-browsers
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/iii-ishida/workrec
    steps:
      - checkout

      - run:
          name: Install gcloud
          command: |
            sudo apt-get install -qqy lsb-release && export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
            sudo apt-get update && sudo apt-get install google-cloud-sdk google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-go

      - run:
          name: Setup glcoud
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet config set core/disable_usage_reporting true
            gcloud --quiet config set component_manager/disable_update_check true

      - run:
          name: Install golint
          command: go get -u golang.org/x/lint/golint

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "server/go.sum" }}

      - run: cd server && go mod download

      - save_cache:
          key: go-mod-v1-{{ checksum "server/go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Unit testing
          command: |
            cd ./server
            gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 & sleep 10; $(gcloud beta emulators datastore env-init) && sh ./test.sh

      - run:
          name: Deploy Server
          command: |
            gcloud --quiet app deploy ./server/command/web/

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - server-test-and-deploy
