version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.0

    working_directory: /go/src/workrec

    environment:
      SDK_VERSION: "1.9.53"

    steps:
      - checkout


      ## Download Appengine SDK

      - restore_cache:
          key: go_appengine_sdk_1.9.53

      - run:
          name: Download appengine sdk
          command: |
            if [ -f ~/google_appengine_${SDK_VERSION}.zip ]; then
              echo "Use cache"
            else
              curl -o ~/google_appengine_${SDK_VERSION}.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-${SDK_VERSION}.zip
            fi

      - save_cache:
          key: go_appengine_sdk_1.9.53
          paths:
            - ~/google_appengine_1.9.53.zip


      ## Install dependencies

      - run:
          name: Install dependencies
          command: |
            unzip -q -d ~/ ~/google_appengine_${SDK_VERSION}.zip
            export PATH=${PATH}:~/go_appengine
            goapp get ./...


      ## Install golint

      - run:
          name: Install golint
          command: go get -u github.com/golang/lint/golint


      # Unit testing

      - run:
          name: Unit testing
          command: |
            export PATH=$PATH:$HOME/go_appengine
            ./test.sh

