require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - workrec_app.rb
    - pb/**/*
    - spec/spec_helper.rb
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*

Lint/ShadowingOuterLocalVariable:
  Severity: convention

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/AutoResourceCleanup:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/StringHashKeys:
  Enabled: true
  Exclude:
    - spec/**/*

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Max: 20
