services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATASTORE_EMULATOR_HOST: "datastore:${EMULATOR_PORT}"
      PORT: 8080
    volumes:
      - .:/app
    depends_on:
      datastore:
        condition: service_healthy
      firebase:
        condition: service_started
    command: uvicorn --host 0.0.0.0 --port 8080 --reload app.main:app
  datastore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    environment:
      DATASTORE_PROJECT_ID: ${GCLOUD_PROJECT}
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${EMULATOR_PORT}"
        ]
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 1s
    command: gcloud beta emulators datastore start --project ${GCLOUD_PROJECT} --host-port 0.0.0.0:${EMULATOR_PORT} --no-store-on-disk --use-firestore-in-datastore-mode
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase_emulator
    ports:
      - "8082:8082"
      - "9099:9099"
    command: firebase emulators:start --project ${GCLOUD_PROJECT} --only auth
