# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dry-struct'
gem 'google-cloud-datastore'
gem 'google-protobuf'
gem 'jwt'
gem 'puma'
gem 'rack'
gem 'roda'

group :development do
  gem 'rake'
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'rspec_junit_formatter'
  gem 'rubocop-rspec'
  gem 'timecop'
end
