name: setup flutter
inputs:
  flutter-version:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-${{ inputs.flutter-version }}-flutter
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: beta
