// Mocks generated by Mockito 5.0.16 from annotations
// in workrec_app/test/widgets/task_list_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'task_list_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [TaskAction].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskAction extends _i1.Mock implements _i2.TaskAction {
  MockTaskAction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> startTask(String? _) =>
      (super.noSuchMethod(Invocation.method(#startTask, [_]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> suspendTask(String? _) =>
      (super.noSuchMethod(Invocation.method(#suspendTask, [_]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> resumeTask(String? _) =>
      (super.noSuchMethod(Invocation.method(#resumeTask, [_]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
