name: firebase CI

on:
  push:
    branches: [ master ]
    paths:
    - 'firebase/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'firebase/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-firebase-cli
        restore-keys: |
          ${{ runner.os }}-node-firebase-cli
    - name: Install firebase cli
      run: npm install -g firebase-tools
    - name: Build and Deploy
      run: firebase deploy -c ./firebase/firebase.json --project ${{ secrets.FIREBASE_APP_PROJECT }} --token=${{ secrets.FIREBASE_TOKEN }}
