name: flutter-client CI

on:
  push:
    branches: [ main ]
    paths:
    - 'flutter-client/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'flutter-client/**'
  workflow_dispatch:

env:
  GOOGLE_SERVICE_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICE_JSON }}
  FLUTTER_VERSION: 2.9.0
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-${{ env.FLUTTER_VERSION }}-flutter
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: beta
    - name: Install firebase cli
      run: npm install -g firebase-tools
    - run: flutter pub global activate flutterfire_cli
    - name: Install dependencies
      run: cd flutter-client && flutter pub get
    - name: Run tests
      run: |-
        cd flutter-client && flutter format --dry-run --set-exit-if-changed . 
        flutterfire configure -p ${{ secrets.FIREBASE_APP_PROJECT }} -i ${{ secrets.IOS_BUNDLE_ID }} -a ${{ secrets.ANDROID_APP_ID }} -m ${{ secrets.IOS_BUNDLE_ID }}
        flutter analyze && flutter test
    - name: Upload goldens if tests fail.
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: goldens
        path: flutter-client/test_goldens/failures/

  golden-test:
    name: golden test
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: beta
    - name: Run golden tests
      run: cd flutter-client && flutter test test_goldens
    - name: Upload goldens if tests fail.
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: goldens
        path: flutter-client/test/pages/failures/

  deploy-doc:
    needs: [build, golden-test]
    name: Deploy doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: beta
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-firebase-cli
        restore-keys: |
          ${{ runner.os }}-node-firebase-cli
    - name: Install firebase cli
      run: npm install -g firebase-tools
    - run: flutter pub global activate dartdoc
    - name: Build and Deploy
      run: |-
        cd flutter-client
        firebase use ${{ secrets.FIREBASE_APP_PROJECT }}
        flutter pub global run dartdoc && firebase target:apply hosting doc ${{ secrets.FIREBASE_APP_PROJECT }}-doc && firebase deploy --only hosting:doc --project ${{ secrets.FIREBASE_APP_PROJECT }} --token=${{ secrets.FIREBASE_TOKEN }}

        # deploy-android:
        #   needs: build
        #   name: Deploy Android
        #   runs-on: ubuntu-latest
        #   steps:
        #   - uses: actions/checkout@v2
        #   - uses: actions/setup-java@v1
        #     with:
        #       java-version: '12.x'
        #   - uses: subosito/flutter-action@v1
        #     with:
        #       channel: beta
        #   - name: Set up Node
        #     uses: actions/setup-node@v2
        #     with:
        #       node-version: '14'
        #   - uses: actions/cache@v2
        #     with:
        #       path: ~/.npm
        #       key: ${{ runner.os }}-node-firebase-cli
        #       restore-keys: |
        #         ${{ runner.os }}-node-firebase-cli
        #   - name: Install firebase cli
        #     run: npm install -g firebase-tools
        #   - name: Build and Deploy
        #     run: |-
        #       cd flutter-client
        #       echo $GOOGLE_SERVICE_JSON > android/app/google-services.json
        #       flutter build apk && firebase appdistribution:distribute ./build/app/outputs/flutter-apk/app-release.apk --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} --token=${{ secrets.FIREBASE_TOKEN }}
